---
title: "COVID19.Rmd"
author: "C. Wu"
date: "2024-04-29"
output: html_document
---
```{r setup, include=FALSE}
#install these packages. I had to look up how to format this correctly so my RMD file would knit correctly
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "https://cran.rstudio.com/"))
required_packages <- c("tidyverse", "lubridate", "plotly", "ggplot2", "caret", "forecast", "randomForest")
new_packages <- required_packages[!(required_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)
library(tidyverse)
library(lubridate)
library(plotly)
library(ggplot2)
library(caret)
library(forecast)
library(randomForest)
```


```{r get_data}

url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

file_names <- c("time_series_covid19_confirmed_US.csv",  "time_series_covid19_confirmed_global.csv", "time_series_covid19_deaths_US.csv",  "time_series_covid19_deaths_global.csv") 

urls<- str_c(url_in, file_names)


```

```{r import_data, message= FALSE}
global_cases <- read_csv(urls[2])
global_deaths <- read_csv(urls[4])
US_cases <- read_csv(urls[1])
US_deaths <- read_csv(urls[3])
```

```{r tidy_global_cases}
global_cases <- global_cases %>%
  pivot_longer(cols = -c('Province/State', 'Country/Region', Lat, Long), names_to = "date", values_to = "cases") %>%
  select(-c(Lat,Long))

global_deaths <- global_deaths %>%
  pivot_longer(cols = -c('Province/State', 'Country/Region', Lat, Long), names_to = "date", values_to = "deaths") %>%
  select(-c(Lat,Long))

global <- global_cases %>%
  full_join(global_deaths) %>%
  rename(Country_Region = 'Country/Region',
         Province_State = 'Province/State') %>%
  mutate(date = mdy(date))

global <- global %>% filter(cases >0)

```

```{r tidy_us_cases}
US_cases %>%
  pivot_longer(cols= -(UID:Combined_Key),
               names_to ="date",
               values_to="cases")



US_cases <- US_cases %>%
  pivot_longer(cols = -(UID:Combined_Key),
               names_to = "date",
               values_to = "cases") %>%
  select(Admin2:cases) %>%
  mutate(date=mdy(date)) %>%
  select(-c(Lat, Long_))


US_deaths <- US_deaths %>%
  pivot_longer(cols = -(UID:Population),
               names_to = "date",
               values_to = "deaths") %>%
  select(Admin2:deaths) %>%
  mutate(date=mdy(date)) %>%
  select(-c(Lat, Long_))


US <- US_cases %>%
  full_join(US_deaths)
```

```{r Joining US and Global}

global <- global %>% 
  unite("Combined_Key", 
        c(Province_State, Country_Region), sep = ',',
        na.rm = TRUE,
        remove = FALSE)


```

```{r Joining population data}

uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"

uid <- read_csv(uid_lookup_url) %>%
  select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))



global <- global %>%
  left_join(uid, by = c("Province_State", "Country_Region")) %>%
  select(-c(UID, FIPS)) %>%
  select(Province_State, Country_Region, date, cases, deaths, Population, Combined_Key)

```


```{r Visualization}
US_by_state <- US %>%
  group_by(Province_State, Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths), 
            Population = sum(Population)) %>%
  mutate(deaths_per_mill = deaths *1000000 / Population) %>%
  select(Province_State, Country_Region, date,
         cases, deaths, deaths_per_mill, Population) %>%
  ungroup()



US_totals <- US_by_state %>%
  group_by(Country_Region, date) %>%
  summarize(cases = sum(cases), deaths = sum(deaths), Population = sum(Population)) %>%
  mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
  select(Country_Region, date, cases, deaths, deaths_per_mill, Population) %>%
  ungroup()



state <- "Colorado"

US_by_state %>%
  filter(Province_State == state) %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date, y = cases)) + geom_line(aes(color = "cases")) + geom_point(aes(color = "cases")) + geom_line(aes(y = deaths, color = "deaths")) + geom_point(aes(y = deaths, color = "deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title = str_c("COVID19 in ", state), y = NULL)
```
```{r analysis}
US_by_state <- US_by_state %>%
  mutate(new_cases = cases - lag(cases),
         new_deaths = deaths - lag(deaths))

US_totals <- US_totals %>%
  mutate(new_cases = cases - lag(cases),
         new_deaths = deaths - lag(deaths))

tail(US_totals)



US_totals %>%
  ggplot(aes(x = date, y = new_cases)) + geom_line(aes(color = "new_cases")) + geom_point(aes(color = "new_cases")) + geom_line(aes(y = new_deaths, color = "new_deaths")) + geom_point(aes(y = new_deaths, color = "new_deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title = "COVID19 in US", y = NULL)

US_by_state %>%
  filter(Province_State == state) %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date, y = new_cases)) + geom_line(aes(color = "new_cases")) + geom_point(aes(color = "new_cases")) + geom_line(aes(y = new_deaths, color = "new_deaths")) + geom_point(aes(y = new_deaths, color = "new_deaths")) + scale_y_log10() + theme(legend.position="bottom", axis.text.x = element_text(angle = 90)) + labs(title = str_c("COVID19 in ", state), y = NULL)


US_state_totals <- US_by_state %>%
  group_by(Province_State) %>%
  summarize(deaths = max(deaths), cases= max(cases),
            population = max(Population),
            cases_per_thou = 1000*cases / population, 
            deaths_per_thou = 1000 * deaths / population) %>%
  filter(cases > 0, population > 0)



US_state_totals %>%
  slice_min(deaths_per_thou, n =10)




```

```{r modeling}
mod <- lm(deaths_per_thou ~ cases_per_thou, data = US_state_totals)
summary(mod)

US_state_totals %>% slice_min(cases_per_thou)
US_state_totals %>% slice_max(cases_per_thou)

x_grid <- seq(1, 151)
new_df <- tibble(cases_per_thou = x_grid)
US_state_totals %>% mutate(pred = predict(mod))


US_total_w_pred <- US_state_totals %>% mutate(pred = predict(mod))
US_total_w_pred

US_total_w_pred %>% ggplot() + geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") + geom_point(aes(x = cases_per_thou, y = pred), color = 'red')


#Here I am adding a polynomial regression to see the non-linear relationship between cases and deaths
US_state_totals$cases_squared <- US_state_totals$cases_per_thou^2
mod_poly <- lm(deaths_per_thou ~ cases_per_thou + cases_squared, data = US_state_totals)
summary(mod_poly)

US_total_w_pred_poly <- US_state_totals %>% mutate(pred = predict(mod_poly))
US_total_w_pred_poly
US_total_w_pred_poly %>% ggplot() + geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") + geom_point(aes(x = cases_per_thou, y = pred), color = 'red')


#Seeing the statistical difference between the two models
anova(mod, mod_poly)


#Trying a random forest model
mod_rf <- randomForest(deaths_per_thou ~ ., data = US_state_totals, ntree = 500, mtry = 2, importance = TRUE)
print(mod_rf)

US_total_w_pred_rf <- US_state_totals %>% mutate(pred = predict(mod_rf))
US_total_w_pred_rf
US_total_w_pred_rf %>% ggplot() + geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") + geom_point(aes(x = cases_per_thou, y = pred), color = 'red')

importance(mod_rf)

print(importance(mod_rf))
```
